#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd

while IFS=':' read username password uid gid description home shell
do
    echo "$username"
    echo "$uid"
    echo "$home"
done < /etc/passwd

