#!/usr/bin/env bash
#using if else Write a Bash script that gives you information about the school file.

if [ -e "school" ]; then
    echo "school file exists"
    if [ -f "school" ]; then                    
        echo "school is a regular file"
        if [ -s "school" ]; then                
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    fi
else
    echo "school file does not exist"
fi

